const profileTypes = {
  GET_PROFILE_FOLLOWERS: `GET_PROFILE_FOLLOWERS`,
  GET_PROFILE_FOLLOWING: `GET_PROFILE_FOLLOWING`,
  SET_PROFILE_FEED: `SET_PROFILE_FEED`,
  SET_PROFILE: `SET_PROFILE`
}

export default profileTypes;