const userTypes = {
  SET_CURRENT_USER: `SET_CURRENT_USER`,
  SET_LOGGED_IN: `SET_LOGGED_IN`,
  SET_LOGGIN_ERROR: `SET_LOGGIN_ERROR`,
  SET_USER_PROFILE: `SET_USER_PROFILE`,
  CREATE_NEW_USER_FROM_ADMIN_STATUS: `CREATE_NEW_USER_FROM_ADMIN_STATUS`,
  PROFILE_UPDATE_STATUS: `PROFILE_UPDATE_STATUS`,
  GET_USER_FEED: `GET_USER_FEED`,
  GET_USER_FOLLOWERS: `GET_USER_FOLLOWERS`,
  GET_USER_FOLLOWING: `GET_USER_FOLLOWING`
}

export default userTypes;
