const tweetTypes = {
  POST_NEW_TWEET: `POST_NEW_TWEET`,
  DELETE_TWEET: `DELETE_TWEET`,
  SET_NEW_TWEET_POPUP_STATUS: `SET_NEW_TWEET_POPUP_STATUS`,
  FAVORITE_TWEET: `FAVORITE_TWEET`,
  RETWEET: `RETWEET`
}

export default tweetTypes;